version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/usr/src/app/.env
    # Elimina el depends_on ya que no hay db local
    command: sh -c "npx prisma migrate deploy && npm run start:prod"