version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    # Solo monta el .env, no otros archivos
    volumes:
      - .env:/usr/src/app/.env:ro
    # Comando simple, las migraciones ya se ejecutaron en el build
    command: npm run start:prod