version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - CURSO_SERVER_PORT=3000  # Puerto interno del contenedor
    # Monta el .env para runtime
    volumes:
      - .env:/usr/src/app/.env:ro
    # Las migraciones se ejecutan en el CMD del Dockerfile