version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .env:/usr/src/app/.env
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
      - "6543:5432" # For connection pooling
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: