# This is a basic workflow to help you get started with Actions

name: CI

# Controla cuándo se ejecutará el flujo de trabajo
on:
  # Activa el flujo de trabajo en eventos de solicitud push o pull, pero solo para la rama "main".
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Le permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:

# Una ejecución de flujo de trabajo se compone de uno o más trabajos que pueden ejecutarse secuencialmente o en paralelo.
jobs:
  # Este flujo de trabajo contiene un único trabajo llamado "construir"
  construir:
    
    # El tipo de corredor en el que se ejecutará el trabajo
    runs-on: ubuntu-latest

    # Los pasos representan una secuencia de tareas que se ejecutarán como parte del trabajo.
    steps:
      # Ejemplo de job 1
      - name: Paso 1
        run: echo ejecución paso 1
