name: Deploy to EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/proyecto
            
            # Pull the latest code
            git fetch origin main
            git reset --hard origin/main
            
            # Create .env if it doesn't exist
            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            
            # Update .env with secrets
            cat > .env << EOF
            CURSO_TEST=App de recetas
            CURSO_SERVER_PORT=80
            SMTP_SERVER=
            SMTP_PORT=
            SMTP_USER=
            SMTP_PASSWORD=
            # Connect to Supabase via connection pooling
            DATABASE_URL="postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:6543/${{ secrets.DB_DATABASE }}?pgbouncer=true"
            # Direct connection to the database. Used for migrations
            DIRECT_URL="postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOST }}:5432/${{ secrets.DB_DATABASE }}"
            CURSO_SERVER_JWT_SECRET=${{ secrets.JWT_SECRET }}
            CURSO_BASE_URL_FRONTEND=
            EOF
            
            # Stop and clean existing containers
            docker compose down || true
            docker system prune --all --force || true
            docker volume prune --force || true
            
            # Build and start new containers
            docker compose up --build -d
            
            # Wait for containers to be ready and run migrations
            sleep 10
            docker compose exec app npx prisma migrate dev --name init || echo "Migrations may have failed, continuing..."